services:
  postgres:
    image: postgres:16-alpine
    container_name: campus-wakppuball-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: campus_wakppuball
      POSTGRES_USER: wakppuball
      POSTGRES_PASSWORD: wakppuball
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
